#!/bin/bash -l
  
#PBS -S /bin/bash
#PBS -q chemx
#PBS -l nodes=1:ppn=24
#PBS -l walltime=00:01:00
#PBS -N test
#PBS -e pbs_error_file.err
#PBS -o pbs_output_file.out
#PBS -V

cd $PBS_O_WORKDIR

t1=`date +%s`

python test.py > josh.out

t2=`date +%s`

echo 'time for job =' $((t2-t1))
