#!/bin/bash -l
  
#PBS -S /bin/bash
#PBS -q metis
#PBS -l nodes=1:ppn=8
#PBS -l walltime=01:00:00
#PBS -N pdmet_test_name
#PBS -e pbs_error_file.err
#PBS -o pbs_output_file.out
#PBS -V

export MKL_NUM_THREADS=8

module load anaconda3/latest

conda activate my_conda_env

cd $PBS_O_WORKDIR

python3 dynamics_test.py > josh.out

