#!/bin/bash -l
  
#PBS -S /bin/bash
#PBS -q chemx
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:01:00
#PBS -N pyscf_test
#PBS -e pbs_error_file.err
#PBS -o pbs_output_file.out
#PBS -V

module load anaconda3/latest

conda activate my_conda_env

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=4

t1=`date +%s`

python pyscftest.py > josh.out

t2=`date +%s`

echo 'time for job =' $((t2-t1))
